language: ruby

rvm:
  - 2.7.0
cache:
  - bundler
services:
  - mysql
before_install:
  - gem install bundler:2.2.29
  - mysql -e 'CREATE DATABASE IF NOT EXISTS sports_portal_test;'
before_script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:schema:load --trace
script:
  - bundle exec rake spec