language: ruby

rvm:
  - 2.7.0
cache:
  - bundler
services:
  - mysql
before_install:
  - gem install bundler:2.2.29
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:shema:load
script:
  - bundle exec rake spec