language: ruby

rvm:
  - 2.7.0
cache:
  - bundler
  - yarn
services:
  - mysql
before_install:
  - nvm install --lts
before_script:
  - bunle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:shema:load
script:
  - bundle exec rake spec